server:
  port: 8601

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmmc?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver