server:
  port: 8801

spring:
  application:
    name: zpheak-api

  #配置nacos注册中心
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: dev


